---
title: "Assignment 1"
output: pdf_document
---

```{r , include = FALSE , warning = FALSE}
# Data Loading and cleaning

rm(list=ls())
library(tidyverse)
library(modelsummary)
library(kableExtra)
library(ggpubr)
library(fixest)
library(xtable)


cps_earnings <- read_csv("https://osf.io/4ay9x/download")

  
  #https://data.nber.org/morg/docs/cpsx.pdf


cps_earnings_filtered <- cps_earnings %>% 
  filter( grade92 >= 44 & grade92 <= 46 ) %>%
  filter( age >= 24 & grade92 <= 65 ) %>% 
  filter( lfsr94 == "Employed-At Work" ) %>%
  filter( uhours >= 20 ) %>% 
  filter( earnwke > 5 )


cps_earnings_filtered <- cps_earnings_filtered %>% 
                         mutate( female =  as.numeric( sex == 2 )) %>%
                         mutate( wages_per_hour = earnwke / uhours) %>%
                         mutate( log_wages_per_hour = log( wages_per_hour )) 

cps_earnings_filtered_teach <- cps_earnings_filtered %>%
          mutate( sample = ifelse( occ2012 == 2200 , 1 , 0 ) ) 

earnings_teachers <- cps_earnings_filtered_teach %>% filter( sample == 1 )

table(earnings_teachers$female)
# 480 males, 471 females

```



```{r , echo = FALSE , warning = FALSE}
# data table

tmp <- earnings_teachers %>% 
      select( female  ,  grade92 ,  
              'Weekly wage' =  earnwke , 
              'Hourly wage' = wages_per_hour ,
              'Ln Hourly wage' = log_wages_per_hour ) %>% 
      mutate( 'Gender' = ifelse(female == 0 , 'Male' , 'Female' ) ,
              'Education' = ifelse(grade92 == 44 , 'Masters' , 
                                      ifelse(grade92 == 45 , 'Prof' , 'PhD' )))

P95 <- function(x){ quantile(x,.95,na.rm=T)}
datasummary( (Gender  + `Education`) * `Weekly wage` + `Hourly wage` + `Ln Hourly wage`  ~ Mean + SD + Min + Max + Median + P95 + N , data = tmp ) %>%  kable_styling(full_width = TRUE , latex_options = "striped" )

```


\pagebreak

```{r , echo = FALSE , warning = FALSE, out.width = "75%"}
# Lowess graphs
p1 <- ggplot( data = earnings_teachers , aes( x = female , y = log_wages_per_hour )) +
  geom_point( color = 'red', size = 2, shape = 16, ) + 
  scale_x_continuous(expand=c(0.01, 0.01), limits = c(0, 1),   breaks=seq(0, 1,   by=1)) + 
  scale_y_continuous(expand=c(0.01, 0.01),limits = c(0, 5), breaks=seq(0, 5, by=1)) +
  geom_smooth( method = 'lm', formula = y ~ x) +
  labs(x = "Gender",y = "Log of wages (USD)")


p2 <- ggplot( data = earnings_teachers , aes( x = grade92, y = log_wages_per_hour )) +
  geom_point( color = 'red', size = 2, shape = 16, ) + 
  scale_x_continuous(expand=c(0.01, 0.01), limits = c(44, 46),   breaks=seq(44, 46,   by=1)) + 
  scale_y_continuous(expand=c(0.01, 0.01),limits = c(0, 5), breaks=seq(0, 5, by=1)) +
  geom_smooth( method = 'lm', formula = y ~ x) +
  labs(x = "Level of Education",y = "Log of wages (USD)")



linear_assoc_figs <- ggarrange(p1, p2,
                              hjust = -0.6,
                              ncol = 1, nrow = 2)
linear_assoc_figs


```

\pagebreak

```{r , echo = FALSE , warning = FALSE}
# Regressions + Regression table

# Log wage ~ Gender
reg0 <- feols( log_wages_per_hour ~ female , data = earnings_teachers , vcov = 'hetero' )

# Log wage ~ Education
reg1 <- feols( log_wages_per_hour ~ grade92 , data = earnings_teachers , vcov = 'hetero' )

# Multiple regression 
reg2 <- feols( log_wages_per_hour ~ female + grade92 , data = earnings_teachers  , vcov = 'hetero' )

earnings_teachers_extra <- earnings_teachers %>% 
                            mutate( master = as.numeric( grade92 == 44 ),
                                    professional = as.numeric( grade92 == 45 ),
                                    phd = as.numeric( grade92 == 46 ) )

# Multivariate Regression with Education as qualitative

reg3 <- feols( log_wages_per_hour ~ female + master + professional , data = earnings_teachers_extra , vcov = 'hetero' )

reg4 <- feols( log_wages_per_hour ~ female + professional + phd , data = earnings_teachers_extra , vcov = 'hetero' )

# Compare the results
# etable( reg0 , reg1 , reg2 , reg3 , reg4 )

#intercept is base variable if x1 is 0, intercept + category 1 is cat1 if x1,x2... is 0 
#cat1,2.... is difference from base

msummary(list(reg0, reg1, reg2, reg3, reg4 ),
         fmt="%.3f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Within|AIC|BIC|R2 Pseudo|Std.Errors',
         stars=c('*' = .05, '**' = .01)
) %>%  kable_styling(full_width = TRUE)


```

